// Auto-generated RIC2 vault records based on user-provided spreadsheet.
// These records will be concatenated onto the existing DEFAULT_VAULTS array
// when this script is loaded. Each entry includes campus, building, and vault ID.
window.DEFAULT_VAULTS = (window.DEFAULT_VAULTS || []).concat([
  { campus: 'RIC2', building: 'DC3', vaultId: 'TMH-27', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC3', vaultId: 'TMH-28', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC3', vaultId: 'TMH-31', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC3', vaultId: 'TMH-32', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC3', vaultId: 'BEV-13', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC3', vaultId: 'BEV-14', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC3', vaultId: 'TMH-104', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'TMH-39', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'TMH-40', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'TMH-43', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'TMH-44', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'TMH-41', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'TMH-42', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'TMH-45', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'TMH-46', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'BEV-17', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'BEV-18', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'BEV-15', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'BEV-16', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'BEV-19', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'BEV-20', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'TMH-105', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC5', vaultId: 'BEV-104', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'TMH 47', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'TMH 48', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'TMH 49', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'TMH 50', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'TMH 51', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'TMH 52', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'TMH 53', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'TMH 54', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'TMH 55', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'TMH 56', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'MMV 03', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'MMV 04', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'CAV 03', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'CAV 03A', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'CAV 04', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'CAV 04A', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'BEV 105', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'BEV 21', progress: 'Not Started', notes: '', author: '' },
  { campus: 'RIC2', building: 'DC6', vaultId: 'BEV 22', progress: 'Not Started', notes: '', author: '' }
]);